### ISSUE TITLE
Peer to Peer Code Review - Team 100 - The Aries

### ISSUE THREAD

**Issue by DennisOsido** [kblycaglayan/Enumerable-Methods#2]
- Most of the team hasn't reached the Ruby portion to comment.
- One of the team members agreed that having a live demo is needed for presenting code.
- One of the team members suggested adding comments to the code to better understand its functionality.
- Good job on the project!

**Comment by kubilaycaglayan** [comment]
Hello Team,

I appreciate your comments,

With all my respect...
